# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: php-actions/phpstan@v3
        with:
          path: app tests
          configuration: phpstan.neon

 
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv
          ini-values: error_reporting=E_ALL
          tools: composer:v2
          coverage: none

      - name: Run composer install
        run: composer install -n --prefer-dist

      - name: Install NPM dependencies
        run: npm i

      - name: Compile assets
        run: npm run build
 
      - name: Prepare Laravel Application
        run: |
          cp .env.ci .env
          php artisan key:generate
 
      - name: Run tests
        run: php artisan test 

      - name: PHPStan Analysis
        run: ./vendor/bin/phpstan analyse -c phpstan.neon 

      - name: Code Formating
        run: php ./vendor/bin/pint --config pint.json